[package]
name = "covid_counter"
version = "0.1.0"
authors = ["Mikhail Chalakov <mikhail@chalakov.net>"]
edition = "2018"

[dependencies]
curl = { version = "0.4.34"}
run_script = "*"
[[bin]]
name = "covid_counter"
path = "main.rs"

